name: CI - Validation (External)

on:
  push:
    paths-ignore: 
      - 'docs/**'
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    name: Validate
    runs-on: macos-latest
    if: github.repository_owner != 'dortania'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python3 -m pip install -r requirements.txt
      - name: Build app
        run: |
          python3 OpenCore-Patcher-GUI.command --validate
